name: Deploy to Play Store

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
      - 'ios/**'

jobs:
  deploy:
    name: Deploy Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build Android app
        run: eas build --platform android --non-interactive

      - name: Setup Google Play Store credentials
        run: |
          echo '${{ secrets.PLAY_STORE_CONFIG_JSON }}' > play-store-credentials.json

      - name: Deploy to Play Store
        run: eas submit -p android --latest
